/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ColaboradorIdRouteImport } from './routes/colaborador.$id'

const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ColaboradorIdRoute = ColaboradorIdRouteImport.update({
  id: '/colaborador/$id',
  path: '/colaborador/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/relatorios': typeof RelatoriosRoute
  '/usuarios': typeof UsuariosRoute
  '/colaborador/$id': typeof ColaboradorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/relatorios': typeof RelatoriosRoute
  '/usuarios': typeof UsuariosRoute
  '/colaborador/$id': typeof ColaboradorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/relatorios': typeof RelatoriosRoute
  '/usuarios': typeof UsuariosRoute
  '/colaborador/$id': typeof ColaboradorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auditoria'
    | '/relatorios'
    | '/usuarios'
    | '/colaborador/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auditoria' | '/relatorios' | '/usuarios' | '/colaborador/$id'
  id:
    | '__root__'
    | '/'
    | '/auditoria'
    | '/relatorios'
    | '/usuarios'
    | '/colaborador/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditoriaRoute: typeof AuditoriaRoute
  RelatoriosRoute: typeof RelatoriosRoute
  UsuariosRoute: typeof UsuariosRoute
  ColaboradorIdRoute: typeof ColaboradorIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colaborador/$id': {
      id: '/colaborador/$id'
      path: '/colaborador/$id'
      fullPath: '/colaborador/$id'
      preLoaderRoute: typeof ColaboradorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditoriaRoute: AuditoriaRoute,
  RelatoriosRoute: RelatoriosRoute,
  UsuariosRoute: UsuariosRoute,
  ColaboradorIdRoute: ColaboradorIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
